spring.application.name=RetailHub

server.port=8080

spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12827896
spring.datasource.username=sql12827896
spring.datasource.password=HZpjLGMlXw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=13882e9fcae69a5db42702b2f47c9b94ec8c7e581132e3eca226048a6d56a0fc
app.jwt.expiration-ms=3600000

razorpay.key-id=rzp_test_ShElYeALrxv3I1
razorpay.key-secret=CnoTQ70hUN9TRQJeWLoX09dc
razorpay.currency=INR

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=retailhub052026@gmail.com
spring.mail.password=ofnfcjhxmccvmscy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true